name: lint
on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js and dependencies
        uses: ./.github/workflows/setup-node

      - name: Run Prettier
        run: pnpm run format

      - name: Run ESLint
        run: pnpm run lint
